# Configuration for evaluating Final Optimized OmniParse results with RapidTable + Hybrid OCR on OmniDocBench
# This config uses our final optimized OmniParse-generated predictions with enhanced table recognition

end2end_eval:
  metrics:
    text_block:
      metric:
        - Edit_dist
        - BLEU
    display_formula:
      metric:
        - Edit_dist
        - CDM
    table:
      metric:
        - TEDS
        - Edit_dist
    reading_order:
      metric:
        - Edit_dist
  dataset:
    dataset_name: end2end_dataset
    ground_truth:
      data_path: ./demo_data/omnidocbench_demo/OmniDocBench_demo.json
    prediction:
      data_path: ./omniparse_final_optimized_results
    match_method: quick_match
